In [1]:
import pandas as pd 
#gives a dataframe with rows and columns for the csv
from sklearn.model_selection import train_test_split 
#splits data into training and testing data
from sklearn.preprocessing import StandardScaler,LabelEncoder
#LabelEncoder → converts text categories to numbers (e.g. "Male"/"Female" → 0/1)
#StandardScaler → scales all numbers to the same range so one big column (like salary) doesn't overpower a small one (like age)
import pickle
#saves trained model to a file

In [2]:
data= pd.read_csv("Churn_Modelling.csv")
data.head() #shows just 5 rows to chk if the data loaded corretcly

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
data=data.drop(['RowNumber','CustomerId','Surname'],axis=1)
#axis=1 means columwise dropping
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [4]:
 #encoding categorical data ---> meaning converting thrm to numbes 
 # so that comp can understand
label_encoder_gender=LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [5]:
#one hot encoding on "geography" column
from sklearn.preprocessing import OneHotEncoder
onehot_encoder_geo=OneHotEncoder()
geo_encoder=onehot_encoder_geo.fit_transform(data[['Geography']]) #geo column se data ko alag alag kiya france germany spain me aur phir unko no assign kare ohe ke through
geo_encoder

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [6]:
geo_encoder.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [7]:
onehot_encoder_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [8]:
geo_encoder_df=pd.DataFrame(geo_encoder.toarray(),columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
#yaha par data aur column ko join kiya pahele hamare pas sirf data that w/o meaning abh usko geo col ke saath join kar diya
geo_encoder_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [9]:
#combininb ohe columns with the original col
data=pd.concat([data.drop('Geography',axis=1),geo_encoder_df],axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [10]:
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)

with open('onehot_encoder_geo.pkl','wb') as file:
    pickle.dump(onehot_encoder_geo,file)

In [11]:
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [12]:
#divide the data into dependent and independent 
# here exited is dependent and rest all is independent
X=data.drop('Exited',axis=1)
y=data['Exited']

#split the data into training and tetsing
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

#scale the features
scaler =StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.fit_transform(X_test)

In [13]:
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

In [14]:
X_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [15]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import TensorBoard,EarlyStopping
import datetime

WARNING:tensorflow:From c:\Users\LOQ\OneDrive\Desktop\ANN\venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [16]:
#Build our ANN model
model=Sequential([
    #input_shape needs to be written for the first hl always for the rest layers no need
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)), #HL1 Connected with input layer
    Dense(32,activation='relu'),#HL2 #no need to give input_shape here bcoz all hidden layers will be connected since we are using sequential
    Dense(1,activation='sigmoid') #outputnlayer   

]
)

WARNING:tensorflow:From c:\Users\LOQ\OneDrive\Desktop\ANN\venv\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

In [17]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [18]:
import tensorflow
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss=tensorflow.keras.losses.BinaryCrossentropy()
loss

In [19]:
#compile the model
model.compile(optimizer=opt,loss='binary_crossentropy',metrics=['accuracy'])

In [ ]:
#set up the Tensorboard
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard

log_dir="logs/fit/+datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [21]:
#set up earlystopping
early_stopping_callback=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [22]:
###TRAINING THE MODELL
history=model.fit(
    X_train,y_train,validation_data=(X_test,y_test),epochs=100,
    callbacks=[tensorflow_callback,early_stopping_callback]
)

Epoch 1/100
WARNING:tensorflow:From c:\Users\LOQ\OneDrive\Desktop\ANN\venv\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From c:\Users\LOQ\OneDrive\Desktop\ANN\venv\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

250/250 [==============================] - 3s 6ms/step - loss: 0.3951 - accuracy: 0.8344 - val_loss: 0.3475 - val_accuracy: 0.8605
Epoch 2/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3543 - accuracy: 0.8541 - val_loss: 0.3552 - val_accuracy: 0.8575
Epoch 3/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3478 - accuracy: 0.8579 - val_loss: 0.3551 - val_accuracy: 0.8570
Epoch 4/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3437 - accuracy: 0.8627 - val_loss: 0.3412 - val_accuracy: 0.8550
Epoch 5/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3445 - accuracy: 0.8581 - val_loss: 0.3432 - val_accuracy: 0.8620
Epoch 6/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3423 - accuracy: 0.8608 - val_loss: 0.3464 - val_accuracy: 0.8590
Epoch 7/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3395 - accuracy: 0.8614 - val_loss: 0.3469 - val_accuracy: 0.8585
Epoch 8/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3370 - accuracy: 0.8649 - val_loss: 0.3554 - val_accuracy: 0.8615
Epoch 9/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3326 - accuracy: 0.8634 - val_loss: 0.3423 - val_accuracy: 0.8590
Epoch 10/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3296 - accuracy: 0.8669 - val_loss: 0.3406 - val_accuracy: 0.8590
Epoch 11/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3277 - accuracy: 0.8637 - val_loss: 0.3496 - val_accuracy: 0.8495
Epoch 12/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3261 - accuracy: 0.8669 - val_loss: 0.3458 - val_accuracy: 0.8585
Epoch 13/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3257 - accuracy: 0.8661 - val_loss: 0.3496 - val_accuracy: 0.8570
Epoch 14/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3201 - accuracy: 0.8706 - val_loss: 0.3502 - val_accuracy: 0.8540
Epoch 15/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3215 - accuracy: 0.8673 - val_loss: 0.3554 - val_accuracy: 0.8510
Epoch 16/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3196 - accuracy: 0.8670 - val_loss: 0.3532 - val_accuracy: 0.8540
Epoch 17/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3147 - accuracy: 0.8699 - val_loss: 0.3580 - val_accuracy: 0.8540
Epoch 18/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3109 - accuracy: 0.8723 - val_loss: 0.3786 - val_accuracy: 0.8485
Epoch 19/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3148 - accuracy: 0.8692 - val_loss: 0.3767 - val_accuracy: 0.8540
Epoch 20/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3063 - accuracy: 0.8745 - val_loss: 0.3715 - val_accuracy: 0.8545

In [23]:
model.save('model.h5')

c:\Users\LOQ\OneDrive\Desktop\ANN\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [24]:
pip install TensorBoard

Requirement already satisfied: TensorBoard in .\venv\Lib\site-packages (2.20.0)
Requirement already satisfied: absl-py>=0.4 in .\venv\Lib\site-packages (from TensorBoard) (2.4.0)
Requirement already satisfied: grpcio>=1.48.2 in .\venv\Lib\site-packages (from TensorBoard) (1.81.1)
Requirement already satisfied: markdown>=2.6.8 in .\venv\Lib\site-packages (from TensorBoard) (3.10.2)
Requirement already satisfied: numpy>=1.12.0 in .\venv\Lib\site-packages (from TensorBoard) (1.26.4)
Requirement already satisfied: packaging in .\venv\Lib\site-packages (from TensorBoard) (26.0)
Requirement already satisfied: pillow in .\venv\Lib\site-packages (from TensorBoard) (12.2.0)
Requirement already satisfied: protobuf!=4.24.0,>=3.19.6 in .\venv\Lib\site-packages (from TensorBoard) (4.25.9)
Requirement already satisfied: setuptools>=41.0.0 in .\venv\Lib\site-packages (from TensorBoard) (82.0.1)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in .\venv\Lib\site-packages (from TensorBoard) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in .\venv\Lib\site-packages (from TensorBoard) (3.1.8)
Requirement already satisfied: typing-extensions~=4.12 in .\venv\Lib\site-packages (from grpcio>=1.48.2->TensorBoard) (4.15.0)
Requirement already satisfied: markupsafe>=2.1.1 in .\venv\Lib\site-packages (from werkzeug>=1.0.1->TensorBoard) (3.0.3)
Note: you may need to restart the kernel to use updated packages.

In [2]:
!pip uninstall -y tensorboard
!pip install tensorboard==2.15.2

Found existing installation: tensorboard 2.20.0
Uninstalling tensorboard-2.20.0:
  Successfully uninstalled tensorboard-2.20.0
Collecting tensorboard==2.15.2
  Using cached tensorboard-2.15.2-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: absl-py>=0.4 in .\venv\Lib\site-packages (from tensorboard==2.15.2) (2.4.0)
Requirement already satisfied: grpcio>=1.48.2 in .\venv\Lib\site-packages (from tensorboard==2.15.2) (1.81.1)
Requirement already satisfied: google-auth<3,>=1.6.3 in .\venv\Lib\site-packages (from tensorboard==2.15.2) (2.55.0)
Requirement already satisfied: google-auth-oauthlib<2,>=0.5 in .\venv\Lib\site-packages (from tensorboard==2.15.2) (1.4.0)
Requirement already satisfied: markdown>=2.6.8 in .\venv\Lib\site-packages (from tensorboard==2.15.2) (3.10.2)
Requirement already satisfied: numpy>=1.12.0 in .\venv\Lib\site-packages (from tensorboard==2.15.2) (1.26.4)
Requirement already satisfied: protobuf!=4.24.0,>=3.19.6 in .\venv\Lib\site-packages (from tensorboard==2.15.2) (4.25.9)
Requirement already satisfied: requests<3,>=2.21.0 in .\venv\Lib\site-packages (from tensorboard==2.15.2) (2.34.2)
Requirement already satisfied: setuptools>=41.0.0 in .\venv\Lib\site-packages (from tensorboard==2.15.2) (69.5.1)
Requirement already satisfied: six>1.9 in .\venv\Lib\site-packages (from tensorboard==2.15.2) (1.17.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in .\venv\Lib\site-packages (from tensorboard==2.15.2) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in .\venv\Lib\site-packages (from tensorboard==2.15.2) (3.1.8)
Requirement already satisfied: pyasn1-modules>=0.2.1 in .\venv\Lib\site-packages (from google-auth<3,>=1.6.3->tensorboard==2.15.2) (0.4.2)
Requirement already satisfied: cryptography>=38.0.3 in .\venv\Lib\site-packages (from google-auth<3,>=1.6.3->tensorboard==2.15.2) (49.0.0)
Requirement already satisfied: requests-oauthlib>=0.7.0 in .\venv\Lib\site-packages (from google-auth-oauthlib<2,>=0.5->tensorboard==2.15.2) (2.0.0)
Requirement already satisfied: charset_normalizer<4,>=2 in .\venv\Lib\site-packages (from requests<3,>=2.21.0->tensorboard==2.15.2) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in .\venv\Lib\site-packages (from requests<3,>=2.21.0->tensorboard==2.15.2) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in .\venv\Lib\site-packages (from requests<3,>=2.21.0->tensorboard==2.15.2) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in .\venv\Lib\site-packages (from requests<3,>=2.21.0->tensorboard==2.15.2) (2026.5.20)
Requirement already satisfied: cffi>=2.0.0 in .\venv\Lib\site-packages (from cryptography>=38.0.3->google-auth<3,>=1.6.3->tensorboard==2.15.2) (2.0.0)
Requirement already satisfied: pycparser in .\venv\Lib\site-packages (from cffi>=2.0.0->cryptography>=38.0.3->google-auth<3,>=1.6.3->tensorboard==2.15.2) (3.0)
Requirement already satisfied: typing-extensions~=4.12 in .\venv\Lib\site-packages (from grpcio>=1.48.2->tensorboard==2.15.2) (4.15.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in .\venv\Lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard==2.15.2) (0.6.3)
Requirement already satisfied: oauthlib>=3.0.0 in .\venv\Lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<2,>=0.5->tensorboard==2.15.2) (3.3.1)
Requirement already satisfied: markupsafe>=2.1.1 in .\venv\Lib\site-packages (from werkzeug>=1.0.1->tensorboard==2.15.2) (3.0.3)
Using cached tensorboard-2.15.2-py3-none-any.whl (5.5 MB)
Installing collected packages: tensorboard
Successfully installed tensorboard-2.15.2

In [1]:
import tensorflow as tf
print(tf.__version__)

WARNING:tensorflow:From c:\Users\LOQ\OneDrive\Desktop\ANN\venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

2.15.0

In [2]:
%load_ext tensorboard

In [6]:
%tensorboard --logdir logs